import type { EconomicFamily } from "../../types/business.js";
import type { CustomerSegment } from "../../types/customerSegment.js";

/**
 * Courbes saisonnières canoniques, 12 multiplicateurs centrés sur 1
 * (index 0 = janvier). Réutilisées à travers les familles pour garder le
 * catalogue simple (spec M11.2.2 §2) — pas une saisonnalité par segment
 * inventée sans raison.
 */
const FLAT: readonly number[] = Array(12).fill(1);
const SUMMER_PEAK: readonly number[] = [0.85, 0.85, 0.9, 0.95, 1.05, 1.2, 1.3, 1.25, 1.0, 0.9, 0.85, 0.85];
const WINTER_PEAK: readonly number[] = [1.25, 1.2, 1.05, 0.95, 0.85, 0.8, 0.8, 0.85, 0.95, 1.05, 1.15, 1.3];
const YEAR_END_PEAK: readonly number[] = [0.9, 0.9, 0.9, 0.9, 0.95, 0.95, 0.95, 0.95, 1.0, 1.05, 1.3, 1.4];

/**
 * Catalogue statique de segments clients par famille (spec §2) : 4 par
 * famille, `relativeSize` sommant à 1, `referencePrice` calibré sur les
 * prix déjà recommandés par `web/src/data/opportunities.ts` (service ~45,
 * hospitality ~26, retail ~15, agency ~6000, subscription ~29). Donnée
 * pure — aucun RNG, aucun état persisté.
 */
const SEGMENTS_BY_FAMILY: Readonly<Record<EconomicFamily, readonly CustomerSegment[]>> = {
  service: [
    {
      id: "service-particuliers-economes",
      label: "Particuliers économes",
      relativeSize: 0.3,
      referencePrice: 30,
      preferredPositioning: "economy",
      priceSensitivity: 0.8,
      qualityExpectation: 40,
      trustImportance: 0.4,
      structuralTrend: 0.0005,
      seasonality: FLAT,
    },
    {
      id: "service-professionnels-locaux",
      label: "Professionnels locaux",
      relativeSize: 0.25,
      referencePrice: 45,
      preferredPositioning: "standard",
      priceSensitivity: 0.5,
      qualityExpectation: 55,
      trustImportance: 0.6,
      structuralTrend: 0.001,
      seasonality: FLAT,
    },
    {
      id: "service-entreprises-exigeantes",
      label: "Entreprises exigeantes",
      relativeSize: 0.3,
      referencePrice: 65,
      preferredPositioning: "premium",
      priceSensitivity: 0.25,
      qualityExpectation: 75,
      trustImportance: 0.8,
      structuralTrend: 0.0015,
      seasonality: FLAT,
    },
    {
      id: "service-copropriétés",
      label: "Copropriétés & gestion immobilière",
      relativeSize: 0.15,
      referencePrice: 40,
      preferredPositioning: "standard",
      priceSensitivity: 0.55,
      qualityExpectation: 50,
      trustImportance: 0.7,
      structuralTrend: 0.0002,
      seasonality: WINTER_PEAK,
    },
  ],
  hospitality: [
    {
      id: "hospitality-habitues-quartier",
      label: "Habitués du quartier",
      relativeSize: 0.4,
      referencePrice: 18,
      preferredPositioning: "economy",
      priceSensitivity: 0.7,
      qualityExpectation: 45,
      trustImportance: 0.5,
      structuralTrend: 0.0003,
      seasonality: FLAT,
    },
    {
      id: "hospitality-familles-weekend",
      label: "Familles le week-end",
      relativeSize: 0.25,
      referencePrice: 24,
      preferredPositioning: "standard",
      priceSensitivity: 0.5,
      qualityExpectation: 55,
      trustImportance: 0.5,
      structuralTrend: 0.0005,
      seasonality: SUMMER_PEAK,
    },
    {
      id: "hospitality-touristes",
      label: "Touristes de passage",
      relativeSize: 0.2,
      referencePrice: 32,
      preferredPositioning: "premium",
      priceSensitivity: 0.3,
      qualityExpectation: 65,
      trustImportance: 0.3,
      structuralTrend: 0.001,
      seasonality: SUMMER_PEAK,
    },
    {
      id: "hospitality-affaires-evenementiel",
      label: "Clientèle affaires & événementiel",
      relativeSize: 0.15,
      referencePrice: 40,
      preferredPositioning: "premium",
      priceSensitivity: 0.25,
      qualityExpectation: 80,
      trustImportance: 0.75,
      structuralTrend: 0.0008,
      seasonality: YEAR_END_PEAK,
    },
  ],
  retail: [
    {
      id: "retail-chasseurs-bonnes-affaires",
      label: "Chasseurs de bonnes affaires",
      relativeSize: 0.35,
      referencePrice: 10,
      preferredPositioning: "economy",
      priceSensitivity: 0.85,
      qualityExpectation: 35,
      trustImportance: 0.3,
      structuralTrend: -0.0003,
      seasonality: FLAT,
    },
    {
      id: "retail-clientele-quartier",
      label: "Clientèle de quartier régulière",
      relativeSize: 0.3,
      referencePrice: 15,
      preferredPositioning: "standard",
      priceSensitivity: 0.5,
      qualityExpectation: 50,
      trustImportance: 0.6,
      structuralTrend: 0.0003,
      seasonality: FLAT,
    },
    {
      id: "retail-amateurs-qualite",
      label: "Amateurs de qualité",
      relativeSize: 0.2,
      referencePrice: 22,
      preferredPositioning: "premium",
      priceSensitivity: 0.3,
      qualityExpectation: 70,
      trustImportance: 0.65,
      structuralTrend: 0.0007,
      seasonality: YEAR_END_PEAK,
    },
    {
      id: "retail-achats-impulsifs",
      label: "Achats impulsifs de passage",
      relativeSize: 0.15,
      referencePrice: 13,
      preferredPositioning: "economy",
      priceSensitivity: 0.6,
      qualityExpectation: 40,
      trustImportance: 0.2,
      structuralTrend: 0.0002,
      seasonality: SUMMER_PEAK,
    },
  ],
  agency: [
    {
      id: "agency-tpe-independants",
      label: "TPE / indépendants",
      relativeSize: 0.3,
      referencePrice: 3_500,
      preferredPositioning: "economy",
      priceSensitivity: 0.75,
      qualityExpectation: 40,
      trustImportance: 0.5,
      structuralTrend: 0.0005,
      seasonality: FLAT,
    },
    {
      id: "agency-pme-croissance",
      label: "PME en croissance",
      relativeSize: 0.35,
      referencePrice: 6_000,
      preferredPositioning: "standard",
      priceSensitivity: 0.45,
      qualityExpectation: 60,
      trustImportance: 0.65,
      structuralTrend: 0.0012,
      seasonality: FLAT,
    },
    {
      id: "agency-entreprises-etablies",
      label: "Entreprises établies",
      relativeSize: 0.2,
      referencePrice: 9_000,
      preferredPositioning: "premium",
      priceSensitivity: 0.25,
      qualityExpectation: 75,
      trustImportance: 0.8,
      structuralTrend: 0.0008,
      seasonality: FLAT,
    },
    {
      id: "agency-grands-comptes",
      label: "Grands comptes ponctuels",
      relativeSize: 0.15,
      referencePrice: 12_000,
      preferredPositioning: "premium",
      priceSensitivity: 0.2,
      qualityExpectation: 80,
      trustImportance: 0.85,
      structuralTrend: 0.0003,
      seasonality: YEAR_END_PEAK,
    },
  ],
  subscription: [
    {
      id: "subscription-independants",
      label: "Indépendants sensibles au prix",
      relativeSize: 0.35,
      referencePrice: 15,
      preferredPositioning: "economy",
      priceSensitivity: 0.8,
      qualityExpectation: 40,
      trustImportance: 0.4,
      structuralTrend: 0.001,
      seasonality: FLAT,
    },
    {
      id: "subscription-petites-equipes",
      label: "Petites équipes",
      relativeSize: 0.3,
      referencePrice: 29,
      preferredPositioning: "standard",
      priceSensitivity: 0.5,
      qualityExpectation: 55,
      trustImportance: 0.6,
      structuralTrend: 0.0015,
      seasonality: FLAT,
    },
    {
      id: "subscription-equipes-etablies",
      label: "Équipes établies",
      relativeSize: 0.2,
      referencePrice: 49,
      preferredPositioning: "premium",
      priceSensitivity: 0.3,
      qualityExpectation: 70,
      trustImportance: 0.7,
      structuralTrend: 0.0012,
      // Cycles budgétaires annuels : renouvellements/nouveaux contrats en fin d'année.
      seasonality: YEAR_END_PEAK,
    },
    {
      id: "subscription-early-adopters",
      label: "Early adopters tech",
      relativeSize: 0.15,
      referencePrice: 35,
      preferredPositioning: "standard",
      priceSensitivity: 0.35,
      qualityExpectation: 60,
      trustImportance: 0.35,
      structuralTrend: 0.002,
      seasonality: FLAT,
    },
  ],
};

export function getMarketSegments(family: EconomicFamily): readonly CustomerSegment[] {
  return SEGMENTS_BY_FAMILY[family];
}
